#ifndef __SSTK_PORTABLE_DEFINE_H_
#define __SSTK_PORTABLE_DEFINE_H_

#define SSTK_ARCH_UNIX 1
#define SSTK_ARCH_WIN32 2
#define SSTK_ARCH_TI_OS 11
#define SSTK_ARCH_FREERTOS 12

#endif // __SSTK_PORTABLE_CONFIG_H
