#ifndef __SSTK_TCP_COMMON__
#define __SSTK_TCP_COMMON__

#include "sstk_socket.h"
#include "sstk_ssl.h"

#define SSTK_TCP_EVT_OPEN 1
#define SSTK_TCP_EVT_CLOSE 2
#define SSTK_TCP_EVT_RECV 3
#define SSTK_TCP_EVT_SSL_OPEN 4
#define SSTK_TCP_EVT_SSL_CLOSE 5

#define SSTK_TCP_ERR_NONE 0
#define SSTK_TCP_ERR_SOCK -1
#define SSTK_TCP_ERR_ABORT -2
#define SSTK_TCP_ERR_SSL -3

#define SSTK_SSL_ERROR_UNINITIALIZED -10
#define SSTK_SSL_ERROR_CA -11
#define SSTK_SSL_ERROR_CERT -12
#define SSTK_SSL_ERROR_KEY -13
#define SSTK_SSL_ERROR_VERIFY -14
#define SSTK_SSL_ERROR_UNKNOWN_TLS_VERSION -10


#define SSTK_TCP_DEFAULT_BUFFER_SIZE 2048

#endif
